ENGINE_ADA = "text-embedding-ata-002"
GPT_DEFAULT = "4"
USE_GEMINI = true
GEMINI_API_KEY = "AIzaSyD76jMkKPAlBeF8YKGrsKRCAwf0nxovpAM"
GEMINI_CHAT_MODEL = "gemini-pro"
GEMINI_EMBEDDING_MODEL = "models/text-embedding-004"
