GEMINI_API_KEY = "AIzaSyD76jMkKPAlBeF8YKGrsKRCAwf0nxovpAM"
ENGINE_ADA = "text-embedding-ata-002"
GPT_DEFAULT = "4"
USE_GEMINI = true
GEMINI_CHAT_MODEL = "gemini-1.5-flash"
GEMINI_EMBEDDING_MODEL = "models/text-embedding-004"
